trigger: none

pool:
  name: Default

steps:
- task: PowerShell@2
  displayName: "Hello World (Safe Mode)"
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Hello World from Self-Hosted Agent"
    pwsh: false
    failOnStderr: true
