trigger: none

pool:
  name: Default

steps:
- task: PowerShell@2
  displayName: "Hello World"
  inputs:
    targetType: inline
    script: |
      Write-Host "Hello World from Azure Pipeline"
    pwsh: false
